### ISSUE TITLE
The developer resources tabs on Eclipse.org project for AJDT has incorrect information

### ISSUE THREAD

**Issue by marioja** [eclipse-aspectj/ajdt#33]
If you go to the tab (https://projects.eclipse.org/projects/tools.ajdt/developer) you are referred to old projects that do not correspond to the current source project.

Also, there is no instructions for developers on how to contribute.  All the current instructions point to Eclipse git repo and processes which I have to assume are obsolete.

Last but not least, there is no readme.md on the master branch to indicate that the useful stuff is on the e423/e426 branch.

**Comment by kriegaex** [comment]
This has been taken care of indirectly by retiring AJDT as a separate Eclipse project, making this repository part of AspectJ as an umbrella project. See Eclipse AJDT Termination and AspectJ Restructuring reviews
  * [EMO issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/475),
  * [review record](https://projects.eclipse.org/projects/tools.ajdt/reviews/eclipse-ajdt-termination-and-eclipse-aspectj-restructuring-review).

That does not improve the overall documentation situation of AJDT, but at least the website has an automatic warning message about possibly outdated content now:

![image](https://github.com/eclipse-aspectj/ajdt/assets/1537384/121a98f0-9bb2-4b8a-bc7f-bb8537a85e9d)
